/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author melih
 */
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;

public class GamePage extends javax.swing.JFrame {

    DbConfClass db=new DbConfClass();
    GamerClass gamer;
    public GamePage() {
        initComponents();
    }
    public GamePage(GamerClass gamer){
        initComponents();
        this.gamer=gamer;
        texting.setText(gamer.getUsername()+" VS PC");
        texting2.setText(gamer.getUsername()+"'s Value:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texting = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        paper = new javax.swing.JButton();
        scissors = new javax.swing.JButton();
        rock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        value = new javax.swing.JLabel();
        texting2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(600, 200, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        texting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        texting.setForeground(new java.awt.Color(255, 255, 255));
        texting.setText("? VS PC");

        score.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setText("Score:");

        score2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        score2.setForeground(new java.awt.Color(255, 255, 255));
        score2.setText("0-0");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rock-paper-scissors.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rock-paper-scissors.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(score2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(texting)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(588, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(27, 27, 27)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(texting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(score2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        paper.setBackground(new java.awt.Color(0, 0, 0));
        paper.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paper.setForeground(new java.awt.Color(255, 255, 255));
        paper.setText("Paper");
        paper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperActionPerformed(evt);
            }
        });

        scissors.setBackground(new java.awt.Color(0, 0, 0));
        scissors.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scissors.setForeground(new java.awt.Color(255, 255, 255));
        scissors.setText("Scissors");
        scissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorsActionPerformed(evt);
            }
        });

        rock.setBackground(new java.awt.Color(0, 0, 0));
        rock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rock.setForeground(new java.awt.Color(255, 255, 255));
        rock.setText("Rock");
        rock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("-");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PC's Value:");

        value.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        value.setForeground(new java.awt.Color(255, 255, 255));

        texting2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texting2.setForeground(new java.awt.Color(255, 255, 255));
        texting2.setText("?'s Value:");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View General Status");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(scissors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(88, 88, 88))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(rock, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(texting2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rock, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(texting2))
                        .addGap(58, 58, 58)
                        .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void inc_game_count(){
        
        String query="Select * from gamers where Username = ?";
        
        try {
            db.psqlquery=db.con.prepareStatement(query);
            db.psqlquery.setString(1,gamer.getUsername());
            ResultSet res=db.psqlquery.executeQuery();
            
            int game_count=0;
            
            while(res.next()){
                game_count=res.getInt("game_count");
            }
            
        query="Update gamers set game_count = ? where Username = ?";
            
            db.psqlquery=db.con.prepareStatement(query);
            db.psqlquery.setInt(1,game_count+1);
            db.psqlquery.setString(2,gamer.getUsername());
            db.psqlquery.executeUpdate();
        
            
            
        } catch (SQLException ex) {
            Logger.getLogger(GamePage.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }
    public void inc_win_count(){
         String query="Select * from gamers where Username = ?";
        
        try {
            db.psqlquery=db.con.prepareStatement(query);
            db.psqlquery.setString(1,gamer.getUsername());
            ResultSet res=db.psqlquery.executeQuery();
            
            int win_count=0;
            
            while(res.next()){
                win_count=res.getInt("win_count");
            }
            
        query="Update gamers set win_count = ? where Username = ?";
            
            db.psqlquery=db.con.prepareStatement(query);
            db.psqlquery.setInt(1,win_count+1);
            db.psqlquery.setString(2,gamer.getUsername());
            db.psqlquery.executeUpdate();
        
            
            
        } catch (SQLException ex) {
            Logger.getLogger(GamePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void rockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockActionPerformed
        inc_game_count();
        String value=RandomVariable();
        String score;
        score=this.score2.getText();
        if(value.equals("Paper")){
            this.value.setText("Paper");
            String[] arr=score.split("-");
            int pc=Integer.parseInt(arr[1]);
            int user=Integer.parseInt(arr[0]);
            pc++;
            score2.setText(user+"-"+pc);
        }
        else if(value.equals("Scissors")){
            inc_win_count();
              this.value.setText("Scissors");
              String[] arr=score.split("-");
            int pc=Integer.parseInt(arr[1]);
            int user=Integer.parseInt(arr[0]);
            user++;
            score2.setText(user+"-"+pc);
        }
        else{
            this.value.setText("Rock");
        }
   
    }//GEN-LAST:event_rockActionPerformed

    private void paperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperActionPerformed
        inc_game_count();
        String value=RandomVariable();
        String score;
        score=this.score2.getText();
        if(value.equals("Scissors")){
            this.value.setText("Scissors");
            String[] arr=score.split("-");
            int pc=Integer.parseInt(arr[1]);
            int user=Integer.parseInt(arr[0]);
            pc++;
            score2.setText(user+"-"+pc);
        }
        else if(value.equals("Rock")){
            inc_win_count();
              this.value.setText("Rock");
              String[] arr=score.split("-");
            int pc=Integer.parseInt(arr[1]);
            int user=Integer.parseInt(arr[0]);
            user++;
            score2.setText(user+"-"+pc);
        }
        else{
            this.value.setText("Paper");
        }
    }//GEN-LAST:event_paperActionPerformed

    private void scissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorsActionPerformed
        inc_game_count();
        String value=RandomVariable();
        String score;
        score=this.score2.getText();
        if(value.equals("Rock")){
            this.value.setText("Rock");
            String[] arr=score.split("-");
            int pc=Integer.parseInt(arr[1]);
            int user=Integer.parseInt(arr[0]);
            pc++;
            score2.setText(user+"-"+pc);
        }
        else if(value.equals("Paper")){
            inc_win_count();
              this.value.setText("Paper");
              String[] arr=score.split("-");
            int pc=Integer.parseInt(arr[1]);
            int user=Integer.parseInt(arr[0]);
            user++;
            score2.setText(user+"-"+pc);
        }
        else{
            this.value.setText("Scissors");
        }
    }//GEN-LAST:event_scissorsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
        Status frame2=new Status(gamer);
        
        frame2.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public String RandomVariable(){
        
        String[] array={"Rock","Paper","Scissors"};
        
        Random rand=new Random();
        
        int random_variable=rand.nextInt(2);
        
        return array[random_variable];
        
    }
    
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton paper;
    private javax.swing.JButton rock;
    private javax.swing.JButton scissors;
    private javax.swing.JLabel score;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel texting;
    private javax.swing.JLabel texting2;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
